Gen onboard
todogroup/governance pull request #166
Opened 2022-01-27 07:35 UTC by justaugustus

Continues https://github.com/todogroup/governance/pull/165.

- onboarding: Init directory
- onboarding: Create onboarding guide for General Members

  This commit splits the General Member onboarding issue template
  into two documents:

  - an issue template for TODO Group PgMs & Steering Committee to
    operationalize access to various TODO Group resources
  - an onboarding guide for new TODO Group members to review to
    ensure they're aware of the various communications channels
    / resources available to them

Signed-off-by: Stephen Augustus <foo@auggie.dev>

2022-01-27 16:35 UTC, anajsana requested changes
This looks great! Know it gets much more organized IMHO, so thanks a lot 😊 I've left some suggestions to `general-member.md`

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +  - [Private channels](#private-channels)
can we call it "General Member" Channels?

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +  - [Private calls](#private-calls)
Can we call it "General Member" calls? 🙂

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +- [OSPO Newsletter](https://www.getrevue.co/profile/osponews)
Actually, everyone has access to the newsletter issues without subscribing to the newsletter (e.g see https://www.getrevue.co/profile/osponews/issues/ospo-news-from-the-todo-group-issue-7-959516). However, if people want to get notifications when the newsletter is sent and have it in their emails, then OSPONews subscription is recommended 👍

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +- [OSPOlogy](https://github.com/todogroup/ospology/discussions) (OSPO Forum Discussions)
I'll call it "OSPO Forum" and people don't have to register to have access to the content (however, if they want to comment on a discussion, they might need to sign in in GitHub)

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +
I'd add an intro description. Something like:

"Public communication channels that need registration wihtin third-party platforms to either see content or interact with content (Slack, LF Community Platform or GitHub)"

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +
Clarify that needs RSVP prior the meeting starts 👍

2022-01-27 16:35 UTC, anajsana commented on onboarding/general-member.md
> +
I would like to add an extra section called "First-time contributions" to at point new members to contribution guidelines and repos where they can start adding their first contributions to TODO:

## Contributing Guidelines

* [OSPO Case Study](https://todogroup.org/guides/casestudies/todo-contribution-guidelines/)
* [TODO Guides](https://todogroup.org/guides/todo-guides-contribution-guidelines/)
* [Whitepapers](https://todogroup.org/guides/whitepaper-guidelines/)
* [OSPOlogy Meetings](https://github.com/todogroup/ospology/tree/main/meetings#what-are-ospology-monthly-meetings)
* [OSPO Survey](https://github.com/todogroup/osposurvey/tree/master/2022#how-to-contribute)

2022-01-28 06:39 UTC, justaugustus commented
> I've left some suggestions to `general-member.md`

@anajsana -- Awesome suggestions! I've integrated them as https://github.com/todogroup/governance/pull/166/commits/840c99d3fd624a5c52a8e15fd42a80a7a6172e4c.

2022-01-28 11:08 UTC, anajsana commented
I think we can merge this. LGTM👏

2022-01-28 12:06 UTC, merged