update ospo associate info
todogroup/governance pull request #226
Opened 2022-06-14 20:43 UTC by anajsana

Signed-off-by: Ana Jimenez Santamaria <ana@todogroup.org>

2022-06-14 21:08 UTC, tsteenbe commented on OSPO-Associate-Program.md
> +TODO Group Community is open to all. Sometimes, there are community participants who wish show their organization efforts on fostering OSPO adoption and enable the worldwide community of practitioner
Community -> community

2022-06-14 21:09 UTC, tsteenbe commented on OSPO-Associate-Program.md
> +Community participants comming from and organization with an established OSPO or similar open source initiative can support TODO becoming `General Members`. To those open source communities or projec
comming -> coming

2022-06-14 21:10 UTC, tsteenbe commented on OSPO-Associate-Program.md
> +Community participants comming from and organization with an established OSPO or similar open source initiative can support TODO becoming `General Members`. To those open source communities or projec
becoming `General Members`. -> by becoming `General Members`.

2022-06-14 21:11 UTC, tsteenbe commented on OSPO-Associate-Program.md
> +Community participants comming from and organization with an established OSPO or similar open source initiative can support TODO becoming `General Members`. To those open source communities or projec
and organization -> an organization

2022-06-15 11:00 UTC, anajsana commented
@tsteenbe @vmbrasseur @ashleywolf @geekygirldawn I've made some edits to my PR to clarify who can qualify for OSPO Associate, its benefits, and how to apply based on your comments from [the SC slack channel conversation](https://thetodogroup.slack.com/archives/C02RLEUHBTP/p1655240557882309). 

Please review this when you have time 👍 Thank you!

2022-06-15 11:32 UTC, tsteenbe requested changes

2022-06-15 11:32 UTC, tsteenbe commented on OSPO-Associate-Program.md
> +* Promotion at TODO Website and main communication channels (TODO mailing lists, newsletter and social media channels)
Website -> website

2022-06-15 11:32 UTC, tsteenbe commented on OSPO-Associate-Program.md
> +TODO Group community is open to all. Sometimes, there are community participants who wish show their organization efforts on fostering OSPO adoption and enable the worldwide community of practitioner
"TODO Group community is open to all." propose we more clear about community vs. members

2022-06-15 12:11 UTC, anajsana commented on OSPO-Associate-Program.md
> +## 💚 Ways to support TODO as an entity
Ok! Then I would also mention that individuals can also support TODO by becoming contributors to the different TODO repos (like OSPOlogy)

2022-06-15 12:14 UTC, anajsana commented on OSPO-Associate-Program.md
> +TODO Group community is open to all. Sometimes, there are community participants who wish show their organization efforts on fostering OSPO adoption and enable the worldwide community of practitioner
I'll add "TODO Group is formed by its Community participants and General Members"

2022-06-15 12:24 UTC, anajsana commented on OSPO-Associate-Program.md
> +TODO Group community is open to all. Sometimes, there are community participants who wish show their organization efforts on fostering OSPO adoption and enable the worldwide community of practitioner
@tsteenbe I'm trying to make clear that people can contribute to TODO resources and participate in TODO sync calls as individuals without applying for GM or Associates program as an organization. That's why "TODO Community is open to all"

2022-06-16 08:11 UTC, anajsana commented
Committed the requested changes from @tsteenbe. I'll merge this PR. Please open a new PR if you'd like to refine this documentation.

2022-06-16 08:12 UTC, merged