Create new Proposal: Open Source in Business
todogroup/governance pull request #336
Opened 2024-06-28 13:59 UTC by anajsana

2024-06-28 14:26 UTC, lhawthorn commented
LGTM, I am supportive of the proposal and want to participate in crafting the document.

2024-06-28 14:40 UTC, BrittanyIstenes commented
+1 - looks good to me as well

2024-06-28 15:23 UTC, justaugustus commented
Since the automatic resolution [vote trigger](https://github.com/todogroup/governance/pull/337) is not merged yet (sorry!):
/vote

2024-07-28 05:17 UTC, justaugustus commented
@todogroup/steering-committee — I'm retriggering this, since the vote timed out:
/vote

2024-07-30 19:51 UTC, ashleywolf commented on resolutions/proposed/2024-28.md
> +Subject: New Focuss Group - Open Source in Business Collaborative Whitepaper / Guide
Focus

2024-08-05 03:03 UTC, justaugustus commented
Between the results of the [previous vote](https://github.com/todogroup/governance/pull/336#issuecomment-2252993871):

<img width="911" alt="Screenshot 2024-08-04 at 19 55 37" src="https://github.com/user-attachments/assets/31113024-686a-440a-82aa-21ca639326c8">

And the [current vote](https://github.com/todogroup/governance/pull/336#issuecomment-2267344545):

<img width="909" alt="Screenshot 2024-08-04 at 19 55 56" src="https://github.com/user-attachments/assets/ee7bce3d-c5c5-42d1-b286-be775afe1a02">

We have 5 @todogroup/steering-committee votes, so this resolution passes.
/cancel vote

2024-08-05 03:03 UTC, justaugustus commented
/vote cancel

2024-08-05 03:04 UTC, justaugustus commented
take 3:
/cancel-vote

2024-08-05 03:11 UTC, justaugustus requested changes
Acknowledging the passing of the resolution and marking status as "Accepted".

2024-08-05 03:11 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +    Stephen Augustus - {approve/decline/abstain/absent}
```suggestion
    Annania Melaku - approve
    Ashley Wolf - approve
    Brittany Istenes - absent
    Georg Kunz - approve
    Leslie Hawthorn - approve
    Nik Peters - absent
    Stephen Augustus - approve
```

ref: https://github.com/todogroup/governance/pull/336#issuecomment-2268082101

2024-08-05 03:11 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +Status: Proposed on 2024-06-24
```suggestion
Status: Accepted
Proposed date: 2024-06-24
```

2024-08-05 03:11 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +Subject: New Focuss Group - Open Source in Business Collaborative Whitepaper / Guide
```suggestion
Subject: New Focus Group - Open Source in Business Collaborative Whitepaper / Guide
```

2024-08-05 03:20 UTC, justaugustus requested changes
@anajsana — I've covered some initial cleanups in https://github.com/todogroup/governance/pull/336/commits/e6e3f4ec35f0c72ed0a1da8c697152f40cb3e513 and left some suggestions/needs in this review. Over to you :)

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
Rename to `resolutions/approved/2024-06-24.md`

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +The following month, during the Touchpoint call on Thursday, June 27th, the community reviewed the interest shared (see comments bellow [here](https://github.com/todogroup/ospology/discussions/481))
```suggestion
The following month, during the Touchpoint call on Thursday, June 27th, the community reviewed the interest shared (see comments [here](https://github.com/todogroup/ospology/discussions/481)) and started to draft a list of challenges and
```

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +WHEREAS, the charter of the TODO Group, dated YYYY-MM-DD, empowers the Steering Committee to {category of action};
Needs update

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +Rationale
Needs update (and heading?)

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +Vote Results
Needs heading?

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +That the committee {approves/declines the proposed action}.
```suggestion
That the committee approves the proposed action.
```

2024-08-05 03:20 UTC, justaugustus commented on resolutions/proposed/2024-28.md
> +The request is for the SC to review this proposal to approve the creation of a new repository under TODO GH org to work collaboratively on the outline of this guide.
```suggestion
The request is for the Steering Committee to review this proposal to approve the creation of a new repository under TODO Group GitHub organization to work collaboratively on the outline of this guide.
```

2024-09-22 11:30 UTC, anajsana commented
/vote

2024-09-25 13:24 UTC, anajsana commented
/cancel-vote

2024-09-25 13:25 UTC, anajsana commented
> Between the results of the [previous vote](https://github.com/todogroup/governance/pull/336#issuecomment-2252993871):
> <img alt="Screenshot 2024-08-04 at 19 55 37" width="911" src="https://private-user-images.githubusercontent.com/567897/354956494-31113024-686a-440a-82aa-21ca639326c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzA3NDAsIm5iZiI6MTcyNzI3MDQ0MCwicGF0aCI6Ii81Njc4OTcvMzU0OTU2NDk0LTMxMTEzMDI0LTY4NmEtNDQwYS04MmFhLTIxY2E2MzkzMjZjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzIwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzkyODZkMTA0YmFkYzVjMDUyZTZiNWQ1MDExNmIzMTVhMDEyY2U4ZTFlMjg3YWUyMTBjOTI4MDNkMjA4MDczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bx9CtlhWIq2yJy-cD0Am_ZDhej_tu2RFVX2V5SDpjRw">
> 
> And the [current vote](https://github.com/todogroup/governance/pull/336#issuecomment-2267344545):
> <img alt="Screenshot 2024-08-04 at 19 55 56" width="909" src="https://private-user-images.githubusercontent.com/567897/354956582-ee7bce3d-c5c5-42d1-b286-be775afe1a02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzA3NDAsIm5iZiI6MTcyNzI3MDQ0MCwicGF0aCI6Ii81Njc4OTcvMzU0OTU2NTgyLWVlN2JjZTNkLWM1YzUtNDJkMS1iMjg2LWJlNzc1YWZlMWEwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMzIwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjIyOTUzZGZkZjc5MDgyODhkM2ZhOWY4MGExZmQyZTgxNDg0MDNmZGY0NjM3Y2E5MTBlNWU2N2Q4Y2U2YTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nrlLTods7URcK1PwV5izh9Pfj99NbauTx_dP-BOrvis">
> 
> We have 5 @todogroup/steering-committee votes, so this resolution passes. /cancel vote

Realized that there was final consensus that this was approved. Thanks all!

2024-09-25 13:28 UTC, anajsana commented on resolutions/proposed/2024-28.md
> +WHEREAS, the charter of the TODO Group, dated YYYY-MM-DD, empowers the Steering Committee to {category of action};
```suggestion
The Steering Committee approves the creation of a new repository under TODO Group GitHub organization to work collaboratively on the outline of this guide;
```

2024-09-25 13:28 UTC, anajsana commented on resolutions/proposed/2024-28.md
> +That the committee approves the proposed action.
```suggestion
That the committee approves the creation of a new repository under TODO Group GitHub organization to work collaboratively on the outline of this guide.
```

2024-09-25 13:28 UTC, anajsana commented on resolutions/proposed/2024-28.md
> +Vote Results
```suggestion
## Vote Results
```

2024-09-25 13:29 UTC, anajsana commented on resolutions/proposed/2024-28.md
> +Resolution YYYY-NN
```suggestion
Resolution 2024-08
```

2024-09-25 13:31 UTC, merged